## An illustration of BLUP
- Two full sibs in same environment
- Known residual and additive genetic variances
  - of trait to be observed: $r=8$, $g=2$
- Mixed model: $\mathbf{Y=Xb+Zu+e}$, with
  - $\mathbf{Z=I}$ (identity matrix)
  - $\mathbf{Y} = \begin{bmatrix}.99\\-.99\end{bmatrix}$

In [6]:
using LinearAlgebra # to make life easier

In [1]:
X = [1., 1] # Julia column vector by default. Remember Julia index start from 1.

2-element Vector{Int64}:
 1
 1

In [3]:
Z = [1 0
     0 1.] # you just write a matrix as a matrix, Julia knows it. The last dot makes the matrix Float64

2×2 Matrix{Float64}:
 1.0  0.0
 0.0  1.0

In [4]:
A = [1 .5
    .5  1]

2×2 Matrix{Float64}:
 1.0  0.5
 0.5  1.0

In [5]:
g, r = 2., 8.  # 2 and 8 will automatically assigned to g and r

(2.0, 8.0)

In [7]:
G = g .* A

2×2 Matrix{Float64}:
 2.0  1.0
 1.0  2.0

In [8]:
R = r * I  # I was defined in LinearAlgebra. Little footprint in memory

UniformScaling{Float64}
8.0*I

In [9]:
y = [.99, -.99]

2-element Vector{Float64}:
  0.99
 -0.99

In [10]:
V = Z * G * Z' + R

2×2 Matrix{Float64}:
 10.0   1.0
  1.0  10.0

In [11]:
Gⁱ, Rⁱ, Vⁱ = inv(G), inv(R), inv(V) # type G\^i<tab> to have Gⁱ

([0.6666666666666666 -0.3333333333333333; -0.3333333333333333 0.6666666666666666], UniformScaling{Float64}(0.125), [0.10101010101010102 -0.010101010101010102; -0.010101010101010102 0.10101010101010101])

In [12]:
ebv₁ = zeros(2) + G * Vⁱ * y

2-element Vector{Float64}:
  0.11000000000000001
 -0.10999999999999997

In [13]:
lhs = [X'Rⁱ * X X'Rⁱ * Z
       Z'Rⁱ * X Z'Rⁱ * Z + Gⁱ]

3×3 Matrix{Float64}:
 0.25    0.125      0.125
 0.125   0.791667  -0.333333
 0.125  -0.333333   0.791667

In [14]:
rhs = [X'Rⁱ * y
       Z'Rⁱ * y]

3-element Vector{Float64}:
  0.0
  0.12375
 -0.12375

In [15]:
ebv₂ = lhs\rhs

3-element Vector{Float64}:
  1.3877787807814457e-17
  0.11
 -0.11000000000000003

```julia
# W01 Assumed known. 
# Exercise that may be calculated by hand ...
# Two full sibs in same environment. 
# Known residual and additive genetic variances 
# of trait to be observed : r = 8, g = 2 .
# Mixed Model :  Y = X b + Z U + e with 
# Z = I(denity), and observations taken as .99 
# and -.99 to make calculation easier

X =  [1 1]'
Z = [1 0 ; 0 1]
A = [1 0.5 ; 0.5 1]
g = 2.0
I = [1 0 ; 0 1]
r = 8.0
G = g * A
R = r * I
V = Z * G * Z' + R

G_ = inv(G)
R_ = inv(R)
V_ = inv(V)

y = [.99 -.99]'

# Predicted breeding values (Karl Pearson regression) :
EU_y = [0 0]'  + G * V_ * y

# MME (Mixed Model Equation) :
C_ = [X' * R_ * X   X' * R_ * Z ;
      Z' * R_ * X   Z' * R_ * Z + G_ ]
C = inv(C_)

RHS = [X' * R_ * y ;
       Z' * R_ * y ]

# Fixed effect estimate and blup breeding values :
U_blup = C * RHS

####################################
# One individual only
G1 = g*A[1,1]
R1 = r*1
V1 = G1 + R1
V1_ = inv(V1)
y1 = 0.99
# Predicted breeding value :
EU1_y1 = 0  + G1 * V1_ * y1
# In plain numbers :
0.2 * .99

#####################################
# For both full sibs with 0.99
y = [.99 .99]'
EU_y = [0 0]'  + G * V_ * y
# (Will not work with MME)
```